name: "Lendable's Sloth"
description: "A GitHub Action that enables optimized and flexible continuous integration suites"
branding:
  icon: git-merge
  color: orange
inputs:
  token:
    description: "GitHub token to use to interact with the GitHub API."
    required: true
  ref:
    description: "Git reference to inspect check runs for. The default supports Pull Requests, Merge Queues as well as branch pushes."
    required: false
    default: ${{ github.event.pull_request.head.sha || github.sha }}
  initial-delay:
    description: "The number of seconds in between polls of the GitHub API for check run conclusions."
    required: false
    default: "5"
  interval:
    description: "Interval in seconds between check of checks (default 5)"
    required: false
    default: "5"
  timeout:
    description: "The number of seconds before the job is declared a failure if check runs have not yet concluded."
    required: false
    default: "300"
  name:
    description: "The name of the Sloth's own check run. This is used to ensure Sloth does not wait upon itself."
    required: false
    default: "sloth"
  ignored:
    description: "A comma separated list of check run names to ignore when determining an overall result."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Await CI outcome
      id: sloth
      shell: bash
      run: |
        ${GITHUB_ACTION_PATH}/bin/sloth.sh \
        ${{ inputs.token }} \
        ${{ inputs.ref }} \
        ${{ github.repository }} \
        ${{ inputs.initial-delay }} \
        ${{ inputs.interval }} \
        ${{ inputs.timeout }} \
        "${{ inputs.name }}" \
        "${{ inputs.ignored }}"
