name: Conventional Commits

on:
  #  https://github.com/marketplace/actions/semantic-pull-request#event-triggers:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: benhodgson87/conventional-pull-request-action@v0.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitlintRulesPath: ".github/commitlint.config.js"
          commitTitleMatch: "false"
          ignoreCommits: "true"
