name: Conventional Commits

on:
  # https://github.com/marketplace/actions/semantic-pull-request#event-triggers
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-24.04
    steps:
      - uses: benhodgson87/conventional-pull-request-action@5cc233b5bbe95b3293e9e464ded984ed47755abe # v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitlintRulesPath: ".github/commitlint.config.cjs"
