name: Verify built files are up to date
on:
  pull_request:
  merge_group:

jobs:
  verify:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Verify that built files are up to date
        run: git diff --exit-code
